Fixed a problem with timezone aware UNTIL values in recurrence rules.
If the recurrence rule contains an ending date (UNTIL) which is timezone aware
this will be parsed by dateutil.rrule.rrulestr() into a timezone aware
datetime instance.

The `recurrence_sequence_ical` deals with timezone-naive instances be design
resulting in a comparison of timezone-aware and timezone-naive datetime
instance which throws the following exception:

  TypeError: can't compare offset-naive and offset-aware datetimes